/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BayRouteImport } from './routes/bay'
import { Route as ConduitRouteImport } from './routes/conduit'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as HuggingfaceRouteImport } from './routes/huggingface'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as VaultRouteImport } from './routes/vault'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BayRoute = BayRouteImport.update({
  id: '/bay',
  path: '/bay',
  getParentRoute: () => rootRouteImport,
} as any)
const ConduitRoute = ConduitRouteImport.update({
  id: '/conduit',
  path: '/conduit',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const HuggingfaceRoute = HuggingfaceRouteImport.update({
  id: '/huggingface',
  path: '/huggingface',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bay': typeof BayRoute
  '/conduit': typeof ConduitRoute
  '/donate': typeof DonateRoute
  '/huggingface': typeof HuggingfaceRoute
  '/subscribe': typeof SubscribeRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bay': typeof BayRoute
  '/conduit': typeof ConduitRoute
  '/donate': typeof DonateRoute
  '/huggingface': typeof HuggingfaceRoute
  '/subscribe': typeof SubscribeRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bay': typeof BayRoute
  '/conduit': typeof ConduitRoute
  '/donate': typeof DonateRoute
  '/huggingface': typeof HuggingfaceRoute
  '/subscribe': typeof SubscribeRoute
  '/vault': typeof VaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bay'
    | '/conduit'
    | '/donate'
    | '/huggingface'
    | '/subscribe'
    | '/vault'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bay'
    | '/conduit'
    | '/donate'
    | '/huggingface'
    | '/subscribe'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/bay'
    | '/conduit'
    | '/donate'
    | '/huggingface'
    | '/subscribe'
    | '/vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BayRoute: typeof BayRoute
  ConduitRoute: typeof ConduitRoute
  DonateRoute: typeof DonateRoute
  HuggingfaceRoute: typeof HuggingfaceRoute
  SubscribeRoute: typeof SubscribeRoute
  VaultRoute: typeof VaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bay': {
      id: '/bay'
      path: '/bay'
      fullPath: '/bay'
      preLoaderRoute: typeof BayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conduit': {
      id: '/conduit'
      path: '/conduit'
      fullPath: '/conduit'
      preLoaderRoute: typeof ConduitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huggingface': {
      id: '/huggingface'
      path: '/huggingface'
      fullPath: '/huggingface'
      preLoaderRoute: typeof HuggingfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BayRoute: BayRoute,
  ConduitRoute: ConduitRoute,
  DonateRoute: DonateRoute,
  HuggingfaceRoute: HuggingfaceRoute,
  SubscribeRoute: SubscribeRoute,
  VaultRoute: VaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
